# Generated by Django 6.0.4 on 2026-04-16 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=50, unique=True, verbose_name='ID du Moteur')),
                ('model_type', models.CharField(default='CFM56-7B', max_length=100)),
                ('status', models.CharField(choices=[('HEALTHY', 'Sain'), ('WARNING', 'Attention (Jaune)'), ('CRITICAL', 'Critique (Rouge)'), ('MAINTENANCE', 'En Réparation')], default='HEALTHY', max_length=20)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('technician_email', models.EmailField(help_text='Email pour les alertes automatiques', max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.company')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_rul_at_alert', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], max_length=10)),
                ('diagnosis', models.TextField(verbose_name='Diagnostic NASA')),
                ('recommended_action', models.TextField(verbose_name='Action Corrective')),
                ('is_resolved', models.BooleanField(default=False)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('cycle_at_alert', models.IntegerField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.engine')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('health_index', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(default=0.0, verbose_name='Altitude (kft)')),
                ('mach', models.FloatField(default=0.0, verbose_name='Nombre de Mach')),
                ('regime', models.FloatField(default=0.0, verbose_name='Régime Moteur (TRA)')),
                ('s2', models.FloatField(verbose_name='Temp Entrée LPC')),
                ('s3', models.FloatField(verbose_name='Temp Sortie HPC')),
                ('s4', models.FloatField(verbose_name='Temp Sortie LPT')),
                ('s7', models.FloatField(verbose_name='Pression Sortie HPC')),
                ('s8', models.FloatField(verbose_name='Vitesse Physique Fan')),
                ('s9', models.FloatField(verbose_name='Vitesse Physique Core')),
                ('s11', models.FloatField(verbose_name='Pression Sortie LPT')),
                ('s12', models.FloatField(verbose_name='Vitesse HPC Sortie')),
                ('s13', models.FloatField(verbose_name='Vitesse LPC Sortie')),
                ('s14', models.FloatField(verbose_name='Vitesse Bypass')),
                ('s15', models.FloatField(verbose_name='Pression Bouchon')),
                ('s17', models.FloatField(verbose_name='Vitesse Rotation HPC')),
                ('s20', models.FloatField(verbose_name='Rapport Pression HPC')),
                ('s21', models.FloatField(verbose_name='Pression Entree Fan')),
                ('predicted_rul', models.FloatField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='maintenance.engine')),
            ],
            options={
                'ordering': ['cycle'],
                'indexes': [models.Index(fields=['engine', '-cycle'], name='maintenance_engine__b33d21_idx'), models.Index(fields=['timestamp'], name='maintenance_timesta_16c65b_idx')],
                'unique_together': {('engine', 'cycle')},
            },
        ),
    ]
