# Generated by Django 6.0.4 on 2026-04-17 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_engine_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancealert',
            options={'ordering': ['-triggered_at']},
        ),
        migrations.RenameField(
            model_name='maintenancealert',
            old_name='probability',
            new_name='risk_score',
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnostic NASA'),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.engine'),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='recommended_action',
            field=models.TextField(blank=True, verbose_name='Action Corrective'),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', '🔴 Critique'), ('WARNING', '🟠 Attention')], default='MEDIUM', max_length=20),
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicted_rul', models.FloatField()),
                ('health_index', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='maintenance.engine')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de Prédiction',
                'verbose_name_plural': 'Historiques de Prédictions',
                'ordering': ['-cycle'],
            },
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.predictionhistory'),
        ),
        migrations.AddIndex(
            model_name='maintenancealert',
            index=models.Index(fields=['engine', '-triggered_at'], name='maintenance_engine__055e19_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancealert',
            index=models.Index(fields=['severity'], name='maintenance_severit_3a0aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancealert',
            index=models.Index(fields=['is_resolved'], name='maintenance_is_reso_7d5c49_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['engine', '-cycle'], name='maintenance_engine__a7f9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['timestamp'], name='maintenance_timesta_d0382f_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionhistory',
            index=models.Index(fields=['status'], name='maintenance_status_55f22a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predictionhistory',
            unique_together={('engine', 'cycle')},
        ),
    ]
