# Generated by Django 6.0.4 on 2026-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancealert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancealert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
