# Generated by Django 6.0.4 on 2026-04-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancealert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_rul', models.FloatField()),
                ('health_index', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('sensor_data', models.JSONField(default=dict)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='maintenance.engine')),
            ],
            options={
                'ordering': ['cycle'],
                'indexes': [models.Index(fields=['engine', 'cycle'], name='maintenance_engine__1840d9_idx')],
                'unique_together': {('engine', 'cycle')},
            },
        ),
    ]
