# Generated by Django 5.2.13 on 2026-05-30 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_enginetimeseries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('epochs', models.IntegerField(default=10)),
                ('samples_count', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=16)),
                ('learning_rate', models.FloatField(default=0.0005)),
                ('rmse_before', models.FloatField(blank=True, null=True)),
                ('rmse_after', models.FloatField(blank=True, null=True)),
                ('r2_before', models.FloatField(blank=True, null=True)),
                ('r2_after', models.FloatField(blank=True, null=True)),
                ('safety_score_before', models.FloatField(blank=True, null=True)),
                ('safety_score_after', models.FloatField(blank=True, null=True)),
                ('performance_level', models.CharField(blank=True, default='', max_length=50)),
                ('global_score', models.FloatField(default=0.0)),
                ('predicted_rul', models.FloatField(blank=True, help_text='RUL prédite sur les données fournies (cycles)', null=True)),
                ('health_status', models.CharField(blank=True, choices=[('HEALTHY', '🟢 Sain - Aucune action requise'), ('WARNING', '🟡 Attention - Surveillance recommandée'), ('CRITICAL', '🔴 Critique - Intervention requise')], default='', help_text='HEALTHY / WARNING / CRITICAL', max_length=20)),
                ('detected_anomalies', models.JSONField(blank=True, default=list, help_text='Liste des capteurs en anomalie avec leurs scores')),
                ('causes', models.JSONField(blank=True, default=list, help_text='Liste des causes probables de la panne')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Liste des actions recommandées')),
                ('urgency_level', models.CharField(blank=True, default='', help_text="Niveau d'urgence : IMMÉDIATE / URGENTE / PLANIFIÉE / PRÉVENTIVE", max_length=50)),
                ('short_message', models.CharField(blank=True, default='', help_text='Message court pour notification', max_length=255)),
                ('long_message', models.TextField(blank=True, default='', help_text="Message détaillé pour l'utilisateur")),
                ('is_viewed', models.BooleanField(default=False, help_text="L'utilisateur a-t-il vu le résultat ?")),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('full_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': "Historique d'entraînement",
                'verbose_name_plural': "Historiques d'entraînements",
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Moteur', 'verbose_name_plural': 'Moteurs'},
        ),
        migrations.AlterModelOptions(
            name='enginetimeseries',
            options={'ordering': ['engine', 'cycle'], 'verbose_name': 'Série Temporelle Moteur', 'verbose_name_plural': 'Séries Temporelles Moteurs'},
        ),
        migrations.AlterModelOptions(
            name='maintenancealert',
            options={'ordering': ['-triggered_at'], 'verbose_name': 'Alerte de Maintenance', 'verbose_name_plural': 'Alertes de Maintenance'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['cycle'], 'verbose_name': 'Donnée Capteur', 'verbose_name_plural': 'Données Capteurs'},
        ),
        migrations.RemoveIndex(
            model_name='enginetimeseries',
            name='maintenance_engine__1840d9_idx',
        ),
        migrations.RemoveField(
            model_name='enginetimeseries',
            name='anomaly_count',
        ),
        migrations.RemoveField(
            model_name='enginetimeseries',
            name='health_index',
        ),
        migrations.RemoveField(
            model_name='enginetimeseries',
            name='predicted_rul',
        ),
        migrations.RemoveField(
            model_name='enginetimeseries',
            name='sensor_data',
        ),
        migrations.RemoveField(
            model_name='enginetimeseries',
            name='status',
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='anomaly_score',
            field=models.FloatField(default=0.0, help_text="0-1 : probabilité d'anomalie", verbose_name="Score d'anomalie"),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='confidence',
            field=models.FloatField(default=1.0, verbose_name='Confiance de la prédiction (0-1)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='fan_degradation',
            field=models.FloatField(default=0.0, verbose_name='Dégradation Fan (%)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='health_score',
            field=models.FloatField(blank=True, help_text='0 = critique, 100 = parfait', null=True, verbose_name='Score de santé (0-100)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='hpc_degradation',
            field=models.FloatField(default=0.0, verbose_name='Dégradation HPC (%)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='hpt_degradation',
            field=models.FloatField(default=0.0, verbose_name='Dégradation HPT (%)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='lpc_degradation',
            field=models.FloatField(default=0.0, verbose_name='Dégradation LPC (%)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='lpt_degradation',
            field=models.FloatField(default=0.0, verbose_name='Dégradation LPT (%)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='rul_remaining',
            field=models.FloatField(blank=True, help_text='Remaining Useful Life prédite', null=True, verbose_name='RUL restante (cycles)'),
        ),
        migrations.AddField(
            model_name='enginetimeseries',
            name='rul_trend',
            field=models.FloatField(blank=True, help_text='Pente de dégradation sur les derniers cycles', null=True, verbose_name='Tendance RUL (pente)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='status',
            field=models.CharField(choices=[('HEALTHY', 'Sain'), ('WARNING', 'Attention'), ('CRITICAL', 'Critique'), ('MAINTENANCE', 'En Réparation')], default='HEALTHY', max_length=20),
        ),
        migrations.AlterField(
            model_name='enginetimeseries',
            name='cycle',
            field=models.PositiveIntegerField(help_text='Cycle de vie du moteur'),
        ),
        migrations.AlterField(
            model_name='enginetimeseries',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Date de la prise en compte', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='is_read',
            field=models.BooleanField(default=False, help_text="Si le technicien a vu l'alerte"),
        ),
        migrations.AlterField(
            model_name='maintenancealert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique'), ('WARNING', 'Attention')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='health_index',
            field=models.FloatField(blank=True, null=True, verbose_name='Indice de Santé'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='predicted_rul',
            field=models.FloatField(blank=True, null=True, verbose_name='RUL Prédite (cycles)'),
        ),
        migrations.AddIndex(
            model_name='engine',
            index=models.Index(fields=['status'], name='maintenance_status_de9ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='engine',
            index=models.Index(fields=['company'], name='maintenance_company_179306_idx'),
        ),
        migrations.AddIndex(
            model_name='enginetimeseries',
            index=models.Index(fields=['engine', '-cycle'], name='maintenance_engine__0e00bf_idx'),
        ),
        migrations.AddIndex(
            model_name='enginetimeseries',
            index=models.Index(fields=['timestamp'], name='maintenance_timesta_9e2a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='enginetimeseries',
            index=models.Index(fields=['health_score'], name='maintenance_health__8dc01c_idx'),
        ),
        migrations.AddIndex(
            model_name='enginetimeseries',
            index=models.Index(fields=['is_anomaly'], name='maintenance_is_anom_3cbd0a_idx'),
        ),
        migrations.AddField(
            model_name='traininghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='traininghistory',
            index=models.Index(fields=['status'], name='maintenance_status_9037d9_idx'),
        ),
        migrations.AddIndex(
            model_name='traininghistory',
            index=models.Index(fields=['user', '-started_at'], name='maintenance_user_id_fe17bd_idx'),
        ),
        migrations.AddIndex(
            model_name='traininghistory',
            index=models.Index(fields=['is_viewed'], name='maintenance_is_view_d8b184_idx'),
        ),
    ]
