# Generated by Django 5.2.13 on 2026-05-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_traininghistory_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininghistory',
            name='health_status',
            field=models.CharField(blank=True, default='', help_text='HEALTHY / WARNING / CRITICAL', max_length=20, null=True),
        ),
    ]
